name: matrix
on: push

jobs:
  get-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check matrix
        run: |
          echo "os=${{ matrix.os }}"
          echo "node=${{ matrix.node }}"
